name: Connector documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCUMENTATION_ROOT: Documentation/_site

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Generate the docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    
    - run: |
        dotnet tool update -g docfx
        docfx Documentation/docfx.json
      
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ${{ env.DOCUMENTATION_ROOT }}

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Run the deployment only on merge/push to main
    if: github.event_name == 'push'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4