name: Connector documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Generate the docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nunit/docfx-action@v2.4.0
      name: Build Documentation
      with:
        args: Documentation/docfx.json